function CodeDefine() { 
this.def = new Array();
this.def["IsrOverrun"] = {file: "ert_main_c.html",line:19,type:"var"};
this.def["isRateRunning"] = {file: "ert_main_c.html",line:20,type:"var"};
this.def["need2runFlags"] = {file: "ert_main_c.html",line:22,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:24,type:"fcn"};
this.def["main"] = {file: "ert_main_c.html",line:97,type:"fcn"};
this.def["SignalGen_rx_B"] = {file: "SignalGen_rx_c.html",line:20,type:"var"};
this.def["SignalGen_rx_DW"] = {file: "SignalGen_rx_c.html",line:23,type:"var"};
this.def["SignalGen_rx_M_"] = {file: "SignalGen_rx_c.html",line:26,type:"var"};
this.def["SignalGen_rx_M"] = {file: "SignalGen_rx_c.html",line:27,type:"var"};
this.def["SignalGen_rx_SetEventsForThisBaseStep"] = {file: "SignalGen_rx_c.html",line:36,type:"fcn"};
this.def["rate_monotonic_scheduler"] = {file: "SignalGen_rx_c.html",line:51,type:"fcn"};
this.def["SignalGen_rx_step0"] = {file: "SignalGen_rx_c.html",line:69,type:"fcn"};
this.def["SignalGen_rx_step1"] = {file: "SignalGen_rx_c.html",line:303,type:"fcn"};
this.def["SignalGen_rx_step2"] = {file: "SignalGen_rx_c.html",line:309,type:"fcn"};
this.def["SignalGen_rx_step"] = {file: "SignalGen_rx_c.html",line:379,type:"fcn"};
this.def["SignalGen_rx_initialize"] = {file: "SignalGen_rx_c.html",line:400,type:"fcn"};
this.def["SignalGen_rx_terminate"] = {file: "SignalGen_rx_c.html",line:784,type:"fcn"};
this.def["B_SignalGen_rx_T"] = {file: "SignalGen_rx_h.html",line:61,type:"type"};
this.def["DW_SignalGen_rx_T"] = {file: "SignalGen_rx_h.html",line:66,type:"type"};
this.def["DAC1"] = {file: "SignalGen_rx_h.html",line:70,type:"var"};
this.def["P_SignalGen_rx_T"] = {file: "SignalGen_rx_types_h.html",line:21,type:"type"};
this.def["RT_MODEL_SignalGen_rx_T"] = {file: "SignalGen_rx_types_h.html",line:24,type:"type"};
this.def["SignalGen_rx_P"] = {file: "SignalGen_rx_data_c.html",line:20,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:27,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:51,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:62,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:86,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:27,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:51,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:25,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:26,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:27,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:28,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:29,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:30,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:36,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:48,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:54,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:60,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:66,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:37,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:44,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:51,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:59,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:73,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["ulonglong_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:77,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:78,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:79,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:89,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:94,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:99,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:106,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:113,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:120,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:127,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:134,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:141,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:148,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:155,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:176,type:"type"};
this.def["scia_rcv"] = {file: "DSP28xx_SciUtil_c.html",line:27,type:"fcn"};
this.def["byteswap_L8cmp"] = {file: "DSP28xx_SciUtil_c.html",line:91,type:"fcn"};
this.def["init_board"] = {file: "MW_c28xx_board_c.html",line:8,type:"fcn"};
this.def["disableWatchdog"] = {file: "MW_c28xx_csl_c.html",line:8,type:"fcn"};
this.def["enable_interrupts"] = {file: "MW_c28xx_csl_c.html",line:16,type:"fcn"};
this.def["init_SCI"] = {file: "MW_c28xx_csl_c.html",line:23,type:"fcn"};
this.def["init_SCI_GPIO"] = {file: "MW_c28xx_csl_c.html",line:62,type:"fcn"};
this.def["config_ePWM_GPIO"] = {file: "MW_c28xx_pwm_c.html",line:8,type:"fcn"};
this.def["SCIBaudRateCalcExternalMode"] = {file: "MW_target_hardware_resources_h.html",line:11,type:"var"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["SignalGen_rx_c.html"] = "../SignalGen_rx.c";
	this.html2Root["SignalGen_rx_c.html"] = "SignalGen_rx_c.html";
	this.html2SrcPath["SignalGen_rx_h.html"] = "../SignalGen_rx.h";
	this.html2Root["SignalGen_rx_h.html"] = "SignalGen_rx_h.html";
	this.html2SrcPath["SignalGen_rx_private_h.html"] = "../SignalGen_rx_private.h";
	this.html2Root["SignalGen_rx_private_h.html"] = "SignalGen_rx_private_h.html";
	this.html2SrcPath["SignalGen_rx_types_h.html"] = "../SignalGen_rx_types.h";
	this.html2Root["SignalGen_rx_types_h.html"] = "SignalGen_rx_types_h.html";
	this.html2SrcPath["SignalGen_rx_data_c.html"] = "../SignalGen_rx_data.c";
	this.html2Root["SignalGen_rx_data_c.html"] = "SignalGen_rx_data_c.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["DSP28xx_SciUtil_c.html"] = "../DSP28xx_SciUtil.c";
	this.html2Root["DSP28xx_SciUtil_c.html"] = "DSP28xx_SciUtil_c.html";
	this.html2SrcPath["DSP28xx_SciUtil_h.html"] = "../DSP28xx_SciUtil.h";
	this.html2Root["DSP28xx_SciUtil_h.html"] = "DSP28xx_SciUtil_h.html";
	this.html2SrcPath["MW_c28xx_board_c.html"] = "../MW_c28xx_board.c";
	this.html2Root["MW_c28xx_board_c.html"] = "MW_c28xx_board_c.html";
	this.html2SrcPath["MW_c28xx_csl_c.html"] = "../MW_c28xx_csl.c";
	this.html2Root["MW_c28xx_csl_c.html"] = "MW_c28xx_csl_c.html";
	this.html2SrcPath["MW_c28xx_pie_h.html"] = "../MW_c28xx_pie.h";
	this.html2Root["MW_c28xx_pie_h.html"] = "MW_c28xx_pie_h.html";
	this.html2SrcPath["MW_c28xx_pwm_c.html"] = "../MW_c28xx_pwm.c";
	this.html2Root["MW_c28xx_pwm_c.html"] = "MW_c28xx_pwm_c.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","SignalGen_rx_c.html","SignalGen_rx_h.html","SignalGen_rx_private_h.html","SignalGen_rx_types_h.html","SignalGen_rx_data_c.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","rtmodel_h.html","DSP28xx_SciUtil_c.html","DSP28xx_SciUtil_h.html","MW_c28xx_board_c.html","MW_c28xx_csl_c.html","MW_c28xx_pie_h.html","MW_c28xx_pwm_c.html","MW_target_hardware_resources_h.html"];
